### ISSUE TITLE
Modern Warfare 2019 showing COD 4

### ISSUE THREAD

**Issue by KypsLloyd** [sirzechs753/PlayStationDiscord-Games#4]
When playing Modern Warfare 2019 the image shows you're playing COD 4 Remastered, text is correct though.
Other games have worked fine.

It also happens when using Tustin's repo. 
Someone already made an issue there but never really got updated.
https://github.com/Tustin/PlayStationDiscord/issues/163

It used to work fine around March-ish. Not entirely sure why this happens.

![image](https://user-images.githubusercontent.com/70693651/128428769-df63f6f8-8ea2-4007-a913-8f4761c685a5.png)

**Comment by sirzechs753** [comment]
could you please provide what titleId u got from apps console?, becuase if u were using my [forked](https://github.com/sirzechs753/PlayStationDiscord) repo, the titleid u got for that specific game title's is "CUSA08829_00" and should get [this image](https://github.com/sirzechs753/PlayStationDiscord-Games/blob/master/ps4/CUSA08829_00.png)
![CUSA08829_00](https://user-images.githubusercontent.com/44752631/128882688-42337f0d-a3fa-44dc-a330-fce6cf8a13d0.png)

**Comment by KypsLloyd** [comment]
Hey, sorry for the late answer but no titleid came from the apps console, only the name. Don't worry about this it's all good :)
