### ISSUE TITLE
Not sure where to find titleid for request.

### ISSUE THREAD

**Issue by KypsLloyd** [sirzechs753/PlayStationDiscord-Games#5]
Hey, I've been playing Bloodborne lately and saw it doesn't have support. 

I don't know exactly what you need to add support for a game, so I'm kind of asking right now. 

![image](https://user-images.githubusercontent.com/70693651/129481904-992f5732-c1d3-4b50-b039-5664d2c3119c.png)

**Comment by sirzechs753** [comment]
The ps4 games titleid comes with prefix "CUSA" for every region, so in your case the titleid is "CUSA03173_00". i'll add it to the repo later this day.

**Comment by KypsLloyd** [comment]
really generous of you for keeping this project up, now that Tustin is inactive, you are appreciated.

**Comment by sirzechs753** [comment]
Added support for Bloodborne in 81ede8d.
Sorry for the late update, I just got back from vacation. Thanks for the appreciation 🙏
