### ISSUE TITLE
one more game request

### ISSUE THREAD

**Issue by KypsLloyd** [sirzechs753/PlayStationDiscord-Games#6]
Hey, was wondering if you could add support for Last of Us Part 2, titleid is "CUSA10249_00".
![image](https://user-images.githubusercontent.com/70693651/129980685-06ae2a89-9a30-4023-9014-139514c83449.png)

this image (or any other image you deem fit):
![image](https://user-images.githubusercontent.com/70693651/129980756-fe1eb1fb-3eea-4a35-8df4-6c15d3562e03.png)

**Comment by sirzechs753** [comment]
Added The Last of Us™ Part II in 1190cb029c281e015b9c0e6ccca848fba271f88e.
Thanks for the contribution 🙂
