### ISSUE TITLE
Game Requests

### ISSUE THREAD

**Issue by Adrixense** [sirzechs753/PlayStationDiscord-Games#9]
Hi there, 

I was wondering if you could add the following games to the project:

CUSA26225_00 - Splitgate

PPSA02181_00 - Guilty Gear -Strive- (It's both on ps4 and ps5 but I can't find the ps4 id for this game, so if you can help me out I would appreciate that a lot)

CUSA01842_00 - Overwatch

PPSA02048_00 - Dead by Daylight (I couldn't find the ps4 id for this one either)

CUSA01606_00 - Skullgirls: 2nd Encore

CUSA11192_00 - Blazblue: Cross Tag Battle

CUSA13338_00 - DOOM Eternal

I apologize for such a long list of games but, you were the only person that I saw trying to keep the project alive. And keep up the fantastic work, your work has shed a light to the long lost project.

**Comment by Adrixense** [comment]
I apologize once again but, I accidentally left out a game

CUSA00419_00 - Grand Theft Auto V

**Comment by sirzechs753** [comment]
Added in 29c1c277dd497d4e275bdb0e67e8d34a11f0b828.
Guilty Gear -Strive- (CUSA19210_00)
Dead by Daylight (CUSA08444_00)
if those 2 games didn't appear as supported, please tell me and give me screenshot of PlaystationDiscord Console showing the titleid like this.
![129481904-992f5732-c1d3-4b50-b039-5664d2c3119c](https://user-images.githubusercontent.com/44752631/130798834-4a3103b3-7341-4da8-bb2c-cfc81f4cd067.png)

**Comment by Adrixense** [comment]
Alright! Will do, thanks for the help

**Comment by Adrixense** [comment]
> Added in [29c1c27](https://github.com/sirzechs753/PlayStationDiscord-Games/commit/29c1c277dd497d4e275bdb0e67e8d34a11f0b828).
> Guilty Gear -Strive- (CUSA19210_00)
> Dead by Daylight (CUSA08444_00)
> if those 2 games didn't appear as supported, please tell me and give me screenshot of PlaystationDiscord Console showing the titleid like this.
> ![129481904-992f5732-c1d3-4b50-b039-5664d2c3119c](https://user-images.githubusercontent.com/44752631/130798834-4a3103b3-7341-4da8-bb2c-cfc81f4cd067.png)

Alright, both Guilty Gear -Strive- and Dead by Daylight work, thanks again for your hard work!
